---
name: App-ZofCMS-Plugin-FileList
version: 0.0101
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: ZofCMS plugin to display lists of files
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0106
  File::Glob: 1.05
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::FileList:
    file: lib/App/ZofCMS/Plugin/FileList.pm
    version: 0.0101
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
